name: bmi_calculator
description: A new Flutter project.

publish_to: "none"

version: 1.0.7+7

environment:
  sdk: ^3.5.3

dependencies:
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_remote_config: ^5.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  in_app_review: ^2.0.9
  package_info_plus: ^8.1.0
  syncfusion_flutter_gauges: ^27.1.56
  url_launcher: ^6.3.0
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
