name: bmi_calculator
description: A new Flutter project.

publish_to: "none"

version: 1.0.9+9

environment:
  sdk: ^3.6.0

dependencies:
  firebase_core: ^3.9.0
  firebase_crashlytics: ^4.2.0
  firebase_remote_config: ^5.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  in_app_review: ^2.0.10
  package_info_plus: ^8.1.2
  syncfusion_flutter_gauges: ^28.1.38
  url_launcher: ^6.3.1
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
